stages:

  - build

  - test

  - deploy

before_script:
  - sudo rm -r -f .vagrant
  
build-server:

  stage: build

  script:
    - echo "build"
deploy-server:
  stage: deploy
  script: 
    - pwd
    - sudo cp package.json ~/deploy_project
    - sudo cp -r public/ ~/deploy_project
    - sudo cp server.js ~/deploy_project
    - cd /home/gitlab-runner/deploy_project
    - sudo vagrant provision --provider=digital_ocean

  environment:
    name: staging
  #only:
  # - master





     
