stages:

  - build

  - test

  - deploy

before_script:
  - sudo rm -r -f .vagrant
  
build-server:

  stage: build

  script:
    - echo "build"
deploy-server:
  stage: deploy
  script: 
    - pwd
    - sudo cp package.json /home/gitlab-runner/deploy_project
    - sudo cp -r public/ /home/gitlab-runner/deploy_project
    - sudo cp server.js /home/gitlab-runner/deploy_project
    - sudo cp Vagrantfile /home/gitlab-runner/
    - cd /home/gitlab-runner/deploy_project
    - sudo vagrant plugin install vagrant-digitalocean
    - sudo vagrant init
    - sudo cp ../Vagrantfile .
    - sudo vagrant up --provider=digital_ocean
    - sudo vagrant provision

  environment:
    name: staging
  #only:
  # - master





     
