stages:

  - build

  - test

  - deploy

build-server:

  stage: build

  script:
    - echo "build"

deploy-server:
  stage: deploy
  script: 
    - pwd
    - ssh -o StrictHostKeyChecking=no -p 24 jla497@csil-cpu470.csil.sfu.ca
   #- scp -o StrictHostKeyChecking=no -P 24 package.json jla497@csil-cpu470.csil.sfu.ca:~/final-project/
   #- sudo scp -r public/ jla497@csil-cpu470.csil.sfu.ca:~/final-project/
   #- sudo scp server.js jla497@csil-cpu470.csil.sfu.ca:~/final-project/
   #- sudo scp Vagrantfile jla497@csil-cpu470.csil.sfu.ca:~/final-project/
   #- ssh -p 24 jla497@csil-cpu470.csil.sfu.ca
   #- cd ~/final-project/
   #- vagrant provision

  environment:
    name: staging
  #only:
  # - master





     
