stages:

  - build

  - test

  - deploy


build-server:

  stage: build

  script:

    - echo "should have separate test and deploy stages for the container"

deploy-server:
  stage: deploy
  script: 
    - sudo vagrant provision

  environment:
    name: staging
  #only:
  # - master





     
