stages:

  - build

  - test

  - deploy

before_script:
  - sudo rm -r -f .vagrant
  
build-server:

  stage: build

  script:
    - echo "build"
deploy-server:
  stage: deploy
  script: 
    - pwd
    - sudo cp package.json ~/deploy_project
    - sudo cp public/ ~/deploy_project
    - sudo cp server.js ~/deploy_project
#    - sudo vagrant provision

  environment:
    name: staging
  #only:
  # - master





     
